"preserve_hierarchy": true

files: [
  {
    "source": "docs/**",
    "translation": "translations/%two_letters_code%/%original_file_name%",
    "ignore": [
      "docs/api/qiskit/**"
      "docs/api/qiskit-ibm-runtime/**"
      "docs/api/qiskit-ibm-provider/**"
    ]
  }
]
